### ISSUE TITLE
InMemory backend doesn't support overwrites/truncates

### ISSUE THREAD

**Issue by marcosscriven** [jvilk/BrowserFS#152] opened 2016-08-18 16:45 UTC
When attempting to ```writeFile``` with an existing path in an ```InMemory``` backend, an ```EEXIST``` error is thrown, regardless of the flags set.

Looking at the code https://github.com/jvilk/BrowserFS/blob/master/src/backend/InMemory.ts, it doesn't seem to make use of ```flag.pathExistsAction()```, unlike other backends like https://github.com/jvilk/BrowserFS/blob/master/src/backend/OverlayFS.ts#L439

I just wondered why there's no common base class for writable backends?

**Comment by jvilk** [comment] 2016-08-18 17:11
> I just wondered why there's no common base class for writable backends?

[There is a single common base class for all backends.](https://github.com/jvilk/BrowserFS/blob/master/src/core/file_system.ts#L490) [There's also one for synchronous file systems.](https://github.com/jvilk/BrowserFS/blob/master/src/core/file_system.ts#L900) The implementation of `open` and `openSync` are there.

In addition to that, there's a (Synchronous/Asynchronous)KeyValueFileSystem abstraction that maps the file system API onto a key-value store. We use the synch version for the `InMemory` and `LocalStorage` APIs, and the async version for `IndexedDB`. The async version could also be used for something like Amazon S3, but I've never had an incentive to implement it.

**Comment by jvilk** [comment] 2016-08-18 17:12
Also, the reason `open()` logic is copied into other backends is for optimization purposes. Without doing that, the default base class will download the entirety of a file every time it is `open()`ed.

**Comment by jvilk** [comment] 2016-08-18 17:12
(Sorry for spamming.) The overall goal of the design is to:

* Make it really easy to write a new backend.
* Make it possible to write a fast backend.

**Comment by jvilk** [comment] 2016-08-18 23:18
@marcosscriven I am unable to reproduce the issue. [Here is a new unit test to test for this problem; it passes.](https://github.com/jvilk/BrowserFS/blob/master/test/tests/fs/all/write-file.js)

Can you provide me with a snippet of code that does not work as expected? Thanks!

**Comment by jvilk** [comment] 2016-10-14 19:02
I was unable to reproduce the issue, so I am closing this issue.

**Closed by jvilk** 2016-10-14 19:02 UTC
Labels: bug, needs more info
