### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by dselman** [jvilk/BrowserFS#165] opened 2016-11-22 23:04 UTC
Mac OS X 10.12.

$ npm --version
4.0.2

$ node --version
v4.6.0

tsc --version
Version 2.0.10

$ npm test

> browserfs@1.1.0 test /Users/dselman/dev/git/BrowserFS
> npm-run-all test:prepare test:karma

> browserfs@1.1.0 test:prepare /Users/dselman/dev/git/BrowserFS
> npm-run-all build:scripts script:make_fixture_loader script:make_test_launcher test:build script:make_zip_fixtures script:make_xhrfs_index

> browserfs@1.1.0 build:scripts /Users/dselman/dev/git/BrowserFS
> tsc -p scripts

node_modules/@types/filesystem/index.d.ts(27,100): error TS2314: Generic type 'ErrorCallback<T>' requires 1 type argument(s).
node_modules/@types/filesystem/index.d.ts(35,89): error TS2314: Generic type 'ErrorCallback<T>' requires 1 type argument(s).
node_modules/@types/filesystem/index.d.ts(40,106): error TS2314: Generic type 'ErrorCallback<T>' requires 1 type argument(s).
node_modules/@types/filesystem/index.d.ts(133,66): error TS2314: Generic type 'ErrorCallback<T>' requires 1 type argument(s).
node_modules/@types/filesystem/index.d.ts(164,99): error TS2314: Generic type 'ErrorCallback<T>' requires 1 type argument(s).
node_modules/@types/filesystem/index.d.ts(181,99): error TS2314: Generic type 'ErrorCallback<T>' requires 1 type argument(s).
node_modules/@types/filesystem/index.d.ts(193,57): error TS2314: Generic type 'ErrorCallback<T>' requires 1 type argument(s).
node_modules/@types/filesystem/index.d.ts(200,70): error TS2314: Generic type 'ErrorCallback<T>' requires 1 type argument(s).
node_modules/@types/filesystem/index.d.ts(226,93): error TS2314: Generic type 'ErrorCallback<T>' requires 1 type argument(s).
node_modules/@types/filesystem/index.d.ts(243,103): error TS2314: Generic type 'ErrorCallback<T>' requires 1 type argument(s).
node_modules/@types/filesystem/index.d.ts(250,68): error TS2314: Generic type 'ErrorCallback<T>' requires 1 type argument(s).
node_modules/@types/filesystem/index.d.ts(268,65): error TS2314: Generic type 'ErrorCallback<T>' requires 1 type argument(s).
node_modules/@types/filesystem/index.d.ts(280,69): error TS2314: Generic type 'ErrorCallback<T>' requires 1 type argument(s).
node_modules/@types/filesystem/index.d.ts(287,55): error TS2314: Generic type 'ErrorCallback<T>' requires 1 type argument(s).
node_modules/@types/filesystem/index.d.ts(368,11): error TS2428: All declarations of 'ErrorCallback' must have identical type parameters.

npm ERR! Darwin 16.0.0
npm ERR! argv "/Users/dselman/.nvm/versions/node/v4.6.0/bin/node" "/Users/dselman/.nvm/versions/node/v4.6.0/bin/npm" "run" "build:scripts"
npm ERR! node v4.6.0
npm ERR! npm  v4.0.2
npm ERR! code ELIFECYCLE
npm ERR! browserfs@1.1.0 build:scripts: `tsc -p scripts`
npm ERR! Exit status 2

**Comment by bengarrett** [comment] 2016-11-25 22:54
This fails for me too both for `npm test` and `npm build`.

Ubuntu 16.04.1
Node v6.9.1
TSC v2.0.10

**Comment by jvilk** [comment] 2016-11-26 15:27
It's not failing on either appveyor or Travis CI or on my local build, but it may be due to cached dependencies. `@types/filesystem` certainly hasn't changed.

I'm currently traveling, but will see if I can reproduce on a fresh clone when I am on a stable internet connection.

**Comment by jvilk** [comment] 2016-11-26 15:39
Appveyor is now showing the failure.

Looks like some typing package has changed recently, so typechecking is failing. Should be a simple fix.

**Comment by remisharrock** [comment] 2016-11-27 02:27
any news ? :-)

**Comment by jvilk** [comment] 2016-11-27 18:11
Okay, I figured it out.

`async` and `FileSystem` type definitions both define incompatible `ErrorCallback` types. Neither module follows best practices, and pollutes the global type namespace.

I can explicitly depend on an older version of the `async` typings, but this problem needs to be fixed upstream.

**Comment by jvilk** [comment] 2016-11-27 18:27
Should be fixed now. I'll change the typings dependency to a newer version once upstream fixes its typings and a new NPM module is released.

**Closed** 2016-11-27 18:27 UTC
Labels: bug
