### ISSUE TITLE
edge case: fs.stat throws 'ENOTDIR' instead of 'ENOENT'

### ISSUE THREAD

**Issue by wmhilton** [jvilk/BrowserFS#205] opened 2017-12-14 05:59 UTC
Edge case, maybe not worth fixing but worth posting on the Internet in case it helps someone.

On Node, if I have a file, say "README.txt" and do `fs.stat('README.txt/.git')` I will get `ENOENT`. However, because README.txt is an actual file, if you do `fs.stat('README.txt/.git')` in BrowserFS you end up getting a different error, 'ENOTDIR', directly from `IndexedDBFileSystem.getDirListing`.

**Comment by jvilk** [comment] 2017-12-19 20:48
Ah, that is an interesting edge case. I'd accept a pull request for a fix.

**Comment by wmhilton** [comment] 2017-12-20 01:31
I've got too much on my plate right now. But I find googling errors and finding the Github issue(s) people have made and the resulting discussions extremely useful, even if the issues are never closed. :)

**Comment by jvilk** [comment] 2018-02-07 23:30
@wmhilton this is not a bug, and is FS dependent. For example, on my Mac, the following happens in Node v9.3.0:

```
> fs.statSync('README.md/fakefile')
Error: ENOTDIR: not a directory, stat 'README.md/fakefile'
    at Object.fs.statSync (fs.js:968:11)
```

Thus, I am closing this as invalid.

**Closed by jvilk** 2018-02-07 23:30 UTC
Labels: bug

**Comment by wmhilton** [comment] 2018-02-08 05:35
I can replicate that result. I get 'ENOTDIR' on a Mac and 'ENOENT' on Windows. So apparently what error to return is not well defined behavior.

Too bad file systems don't use HTTP statuses; then it would just be '404 Not Found'.
