### ISSUE TITLE
Cannot create browserfs.js via npm install - no way to create distribution

### ISSUE THREAD

**Issue by javadesigner1** [jvilk/BrowserFS#363] opened 2023-08-06 23:14 UTC
Hello:

Am on latest macOS - with latest xcode tools installed. node, yarn, npm all installed (node v20.x)

Pulled browserFS.

Ran both yarn install and npm install and neither created a browserfs.js or browserfs.min.js 

Please attached files (i've blurred out some personal info from the path names). Any help will be appreciated!

![b](https://github.com/jvilk/BrowserFS/assets/141592229/a4f12089-aeb4-46d7-b148-de97d0c5a46c)

**Comment by javadesigner1** [comment] 2023-08-06 23:24
I also tried running: 

**_npm run dist_**

which chugged along and in the end gave the following error:

![c](https://github.com/jvilk/BrowserFS/assets/141592229/fb8c1a5d-89db-45bb-a518-847a0f5546b1)
![d](https://github.com/jvilk/BrowserFS/assets/141592229/04332a69-4ac0-4e39-9d1d-635f8fa3d325)

**Comment by dr-vortex** [comment] 2023-08-07 01:35
The new build system does not use any `dist` commands. Please do `npm run build`.

I'm working on getting the CI/CD system overhauled right now and will remove the old commands soon.

**Comment by dr-vortex** [comment] 2023-08-24 00:55
Duplicate of #361

**Closed by dr-vortex** 2023-08-24 00:55 UTC
