### ISSUE TITLE
BrowserFS not working with webpack

### ISSUE THREAD

**Issue by jman13378** [jvilk/BrowserFS#368] opened 2023-09-09 18:21 UTC
when i dont use `configure` i get `VM1210:5 Uncaught Error: Error: EIO: Initialize BrowserFS with a file system using BrowserFS.initialize(filesystem)`
when i use `configure ` i get `Uncaught TypeError: e is not a function`
code that uses BFS
```
const fr = require("browserfs");
fr.configure({ fs: "LocalStorage" });

delete window.localStorage;

window.TwetzelWebPackChunk[5858][3] = fr.BFSRequire("fs");
```
<details>
<summary>webpack config</summary>

```js
const path = require("path");
var { FilerWebpackPlugin } = require("filer/webpack");
const webpack = require("webpack");

module.exports = {
  resolve: {
    // Use our versions of Node modules.
    alias: {
      fs: "browserfs/dist/shims/fs.js",
      buffer: "browserfs/dist/shims/buffer.js",
      path: "browserfs/dist/shims/path.js",
      processGlobal: "browserfs/dist/shims/process.js",
      bufferGlobal: "browserfs/dist/shims/bufferGlobal.js",
      bfsGlobal: require.resolve("browserfs"),
    },

    fallback: {
      fs: require.resolve("browserify-fs"),
      stream: require.resolve("stream-browserify"),
      buffer: require.resolve("buffer"),
    },
  },
  entry: "./src/index.js",
  mode: "production",
  output: {
    filename: "main.js",

    path: path.resolve(__dirname, "dist"),
  },
  plugins: [new webpack.ProvidePlugin({ BrowserFS: "bfsGlobal", process: "processGlobal", Buffer: "bufferGlobal" }), new FilerWebpackPlugin()],

};

```
</details>

**Comment by dr-vortex** [comment] 2023-09-09 20:57
@jman13378 Which version of browserfs are you using?

**Comment by jman13378** [comment] 2023-09-10 01:32
idk latest

**Comment by dr-vortex** [comment] 2023-09-10 14:01
If you're using the latest from NPM, it will not have the latest bug fixes and features. Please read [Releases and compatibility going forward](https://github.com/jvilk/BrowserFS#releases-and-compatibility-going-forward). 

Try building it from source. That should fix the issue:

```
git clone https://github.com/jvilk/BrowserFS
cd BrowserFS
npm i
npm run build
```

**Comment by jman13378** [comment] 2023-09-10 15:32
where do i clone it

**Comment by dr-vortex** [comment] 2023-09-10 18:34
Please clone it in a separate directory. You can then symlink the BrowserFS in node_modules to it.

For example (from your project):
```sh
cd ..
git clone https://github.com/jvilk/browserfs
cd browserfs 
npm i
npm run build
cd ../your-project
rm -rf node_modules/browserfs
ln -s ../browserfs node_modules/browserfs
```

**Comment by jman13378** [comment] 2023-09-10 19:03
now when i run my build command i get this

<details>
<summary>Error</summary>

```diff
ERROR in ./node_modules/debug/src/browser.js 226:18-25
Module not found: Error: Can't resolve 'processGlobal' in 'D:\webpack\node_modules\debug\src'
 @ ./node_modules/socket.io-client/build/cjs/index.js 12:32-48
 @ ./src/index.js 47:38-65

ERROR in ./node_modules/filer/lib/async.js 15:15-22
Module not found: Error: Can't resolve 'processGlobal' in 'D:\webpack\node_modules\filer\lib'
 @ ./node_modules/filer/src/shell/shell.js 5:12-41
 @ ./node_modules/filer/src/index.js 11:9-36
 @ ./node_modules/filer/shims/path.js 1:17-40
 @ ./node_modules/ejs/lib/ejs.js 50:11-26
 @ ./src/index.js 38:38-52

ERROR in ./node_modules/filer/node_modules/schema-utils/dist/validate.js 133:6-13
Module not found: Error: Can't resolve 'processGlobal' in 'D:\webpack\node_modules\filer\node_modules\schema-utils\dist'
 @ ./node_modules/filer/node_modules/schema-utils/dist/index.js 9:4-25
 @ ./node_modules/filer/src/webpack-plugin/utils.js 1:19-42
 @ ./node_modules/filer/src/webpack-plugin/index.js 2:12-30
 @ ./node_modules/filer/src/index.js 21:22-49
 @ ./node_modules/filer/shims/path.js 1:17-40
 @ ./node_modules/ejs/lib/ejs.js 50:11-26
 @ ./src/index.js 38:38-52

ERROR in ./node_modules/filer/src/filesystem/implementation.js 707:17-23
Module not found: Error: Can't resolve 'bufferGlobal' in 'D:\webpack\node_modules\filer\src\filesystem'
 @ ./node_modules/filer/src/filesystem/interface.js 32:13-43
 @ ./node_modules/filer/src/index.js 5:14-50
 @ ./node_modules/filer/shims/path.js 1:17-40
 @ ./node_modules/ejs/lib/ejs.js 50:11-26
 @ ./src/index.js 38:38-52

ERROR in ./node_modules/filer/src/filesystem/interface.js 81:9-15
Module not found: Error: Can't resolve 'bufferGlobal' in 'D:\webpack\node_modules\filer\src\filesystem'
 @ ./node_modules/filer/src/index.js 5:14-50
 @ ./node_modules/filer/shims/path.js 1:17-40
 @ ./node_modules/ejs/lib/ejs.js 50:11-26
 @ ./src/index.js 38:38-52

ERROR in ./node_modules/filer/src/index.js 6:10-16
Module not found: Error: Can't resolve 'bufferGlobal' in 'D:\webpack\node_modules\filer\src'
 @ ./node_modules/filer/shims/path.js 1:17-40
 @ ./node_modules/ejs/lib/ejs.js 50:11-26
 @ ./src/index.js 38:38-52

ERROR in ./node_modules/filer/src/path.js 5:0-7
Module not found: Error: Can't resolve 'processGlobal' in 'D:\webpack\node_modules\filer\src'
 @ ./node_modules/filer/src/index.js 8:8-28 9:8-28
 @ ./node_modules/filer/shims/path.js 1:17-40
 @ ./node_modules/ejs/lib/ejs.js 50:11-26
 @ ./src/index.js 38:38-52

ERROR in ./node_modules/filer/src/providers/indexeddb.js 61:19-25
Module not found: Error: Can't resolve 'bufferGlobal' in 'D:\webpack\node_modules\filer\src\providers'
 @ ./node_modules/filer/src/providers/index.js 1:18-43
 @ ./node_modules/filer/shims/providers/default.js 1:20-56
 @ ./node_modules/filer/shims/fs.js 5:13-34 8:13-43
 @ ./node_modules/ejs/lib/ejs.js 48:9-22
 @ ./src/index.js 38:38-52

ERROR in ./node_modules/filer/src/webpack-plugin/processors.js 4:12-19
Module not found: Error: Can't resolve 'processGlobal' in 'D:\webpack\node_modules\filer\src\webpack-plugin'
 @ ./node_modules/filer/src/webpack-plugin/index.js 7:27-50
 @ ./node_modules/filer/src/index.js 21:22-49
 @ ./node_modules/filer/shims/path.js 1:17-40
 @ ./node_modules/ejs/lib/ejs.js 50:11-26
 @ ./src/index.js 38:38-52

ERROR in ./node_modules/path/path.js 25:16-23
Module not found: Error: Can't resolve 'processGlobal' in 'D:\webpack\node_modules\path'
 @ ./node_modules/filer/src/path.js 12:17-32
 @ ./node_modules/filer/src/index.js 8:8-28 9:8-28
 @ ./node_modules/filer/shims/path.js 1:17-40
 @ ./node_modules/ejs/lib/ejs.js 50:11-26
 @ ./src/index.js 38:38-52

ERROR in ./node_modules/util/util.js 73:6-13
Module not found: Error: Can't resolve 'processGlobal' in 'D:\webpack\node_modules\util'
 @ ./node_modules/path/path.js 26:11-26
 @ ./node_modules/filer/src/path.js 12:17-32
 @ ./node_modules/filer/src/index.js 8:8-28 9:8-28
 @ ./node_modules/filer/shims/path.js 1:17-40
 @ ./node_modules/ejs/lib/ejs.js 50:11-26
 @ ./src/index.js 38:38-52

ERROR in ./node_modules/engine.io-client/build/cjs/transports/websocket.js 96:51-57
Module not found: Error: Can't resolve 'bufferGlobal' in 'D:\webpack\node_modules\engine.io-client\build\cjs\transports'
 @ ./node_modules/engine.io-client/build/cjs/transports/index.js 5:23-48
 @ ./node_modules/engine.io-client/build/cjs/index.js 9:17-49
 @ ./node_modules/socket.io-client/build/cjs/url.js 7:27-54
 @ ./node_modules/socket.io-client/build/cjs/index.js 7:17-36
 @ ./src/index.js 47:38-65

ERROR in ./node_modules/ajv-keywords/keywords/instanceof.js
Cannot read properties of undefined (reading 'module')
 @ ./node_modules/ajv-keywords/keywords/index.js 4:16-39
 @ ./node_modules/ajv-keywords/index.js 3:15-36
 @ ./node_modules/filer/node_modules/schema-utils/dist/validate.js 58:22-45
 @ ./node_modules/filer/node_modules/schema-utils/dist/index.js 9:4-25
 @ ./node_modules/filer/src/webpack-plugin/utils.js 1:19-42
 @ ./node_modules/filer/src/webpack-plugin/index.js 2:12-30
 @ ./node_modules/filer/src/index.js 21:22-49
 @ ./node_modules/filer/shims/path.js 1:17-40
 @ ./node_modules/ejs/lib/ejs.js 50:11-26
 @ ./src/index.js 38:38-52

ERROR in ./node_modules/debug/src/browser.js
Cannot read properties of undefined (reading 'module')
 @ ./node_modules/socket.io-client/build/cjs/index.js 12:32-48
 @ ./src/index.js 47:38-65

ERROR in ./node_modules/filer/lib/async.js
Cannot read properties of undefined (reading 'module')
 @ ./node_modules/filer/src/shell/shell.js 5:12-41
 @ ./node_modules/filer/src/index.js 11:9-36
 @ ./node_modules/filer/shims/path.js 1:17-40
 @ ./node_modules/ejs/lib/ejs.js 50:11-26
 @ ./src/index.js 38:38-52

ERROR in ./node_modules/filer/node_modules/schema-utils/dist/validate.js
Cannot read properties of undefined (reading 'module')
 @ ./node_modules/filer/node_modules/schema-utils/dist/index.js 9:4-25
 @ ./node_modules/filer/src/webpack-plugin/utils.js 1:19-42
 @ ./node_modules/filer/src/webpack-plugin/index.js 2:12-30
 @ ./node_modules/filer/src/index.js 21:22-49
 @ ./node_modules/filer/shims/path.js 1:17-40
 @ ./node_modules/ejs/lib/ejs.js 50:11-26
 @ ./src/index.js 38:38-52

ERROR in ./node_modules/filer/src/filesystem/implementation.js
Cannot read properties of undefined (reading 'module')
 @ ./node_modules/filer/src/filesystem/interface.js 32:13-43
 @ ./node_modules/filer/src/index.js 5:14-50
 @ ./node_modules/filer/shims/path.js 1:17-40
 @ ./node_modules/ejs/lib/ejs.js 50:11-26
 @ ./src/index.js 38:38-52

ERROR in ./node_modules/filer/src/filesystem/interface.js
Cannot read properties of undefined (reading 'module')
 @ ./node_modules/filer/src/index.js 5:14-50
 @ ./node_modules/filer/shims/path.js 1:17-40
 @ ./node_modules/ejs/lib/ejs.js 50:11-26
 @ ./src/index.js 38:38-52

ERROR in ./node_modules/filer/src/index.js
Cannot read properties of undefined (reading 'module')
 @ ./node_modules/filer/shims/path.js 1:17-40
 @ ./node_modules/ejs/lib/ejs.js 50:11-26
 @ ./src/index.js 38:38-52

ERROR in ./node_modules/filer/src/path.js
Cannot read properties of undefined (reading 'module')
 @ ./node_modules/filer/src/index.js 8:8-28 9:8-28
 @ ./node_modules/filer/shims/path.js 1:17-40
 @ ./node_modules/ejs/lib/ejs.js 50:11-26
 @ ./src/index.js 38:38-52

ERROR in ./node_modules/filer/src/providers/indexeddb.js
Cannot read properties of undefined (reading 'module')
 @ ./node_modules/filer/src/providers/index.js 1:18-43
 @ ./node_modules/filer/shims/providers/default.js 1:20-56
 @ ./node_modules/filer/shims/fs.js 5:13-34 8:13-43
 @ ./node_modules/ejs/lib/ejs.js 48:9-22
 @ ./src/index.js 38:38-52

ERROR in ./node_modules/filer/src/webpack-plugin/processors.js
Cannot read properties of undefined (reading 'module')
 @ ./node_modules/filer/src/webpack-plugin/index.js 7:27-50
 @ ./node_modules/filer/src/index.js 21:22-49
 @ ./node_modules/filer/shims/path.js 1:17-40
 @ ./node_modules/ejs/lib/ejs.js 50:11-26
 @ ./src/index.js 38:38-52

ERROR in ./node_modules/path/path.js
Cannot read properties of undefined (reading 'module')
 @ ./node_modules/filer/src/path.js 12:17-32
 @ ./node_modules/filer/src/index.js 8:8-28 9:8-28
 @ ./node_modules/filer/shims/path.js 1:17-40
 @ ./node_modules/ejs/lib/ejs.js 50:11-26
 @ ./src/index.js 38:38-52

ERROR in ./node_modules/util/util.js
Cannot read properties of undefined (reading 'module')
 @ ./node_modules/path/path.js 26:11-26
 @ ./node_modules/filer/src/path.js 12:17-32
 @ ./node_modules/filer/src/index.js 8:8-28 9:8-28
 @ ./node_modules/filer/shims/path.js 1:17-40
 @ ./node_modules/ejs/lib/ejs.js 50:11-26
 @ ./src/index.js 38:38-52

ERROR in ./node_modules/engine.io-client/build/cjs/transports/websocket.js
Cannot read properties of undefined (reading 'module')
 @ ./node_modules/engine.io-client/build/cjs/transports/index.js 5:23-48
 @ ./node_modules/engine.io-client/build/cjs/index.js 9:17-49
 @ ./node_modules/socket.io-client/build/cjs/url.js 7:27-54
 @ ./node_modules/socket.io-client/build/cjs/index.js 7:17-36
 @ ./src/index.js 47:38-65

26 errors have detailed information that is not shown.
Use 'stats.errorDetails: true' resp. '--stats-error-details' to show it.

webpack 5.88.2 compiled with 26 errors in 9865 ms
```
</details>

**Comment by dr-vortex** [comment] 2023-09-10 19:29
I don't see any issues with BrowserFS. What does index.js look like?

I recently removed the various polyfills exported by BrowserFS (path, process, buffer, etc.). The change was made because BrowserFS is not intended to polyfill those APIs. If you need to polyfill them, you can install a polyfill separately.  Moreover, the polyfills used (bfs-path, bfs-process, etc.) were old and did not support the standard APIs correctly.

Those polyfills may have defined the missing `globalName` variables, which would have led to those errors. Regardless, having the index.js code would help me understand the problem better.

**Comment by jman13378** [comment] 2023-09-10 20:37
```js
import _ from "lodash";

window["privateLocalStorage"] = window.localStorage;
delete window.clearInterval;

const Twetzel = {
  /** General Objects */
  5858: {
    /** */ 1: Object,
    /** .*/ 2: Object,
    /** */ 3: Object,
    /** */ 4: Object,
    /** */ 5: Object,
    /** */ 6: Object,
    /** */ 7: Object,
    /** */ 8: Object,
    /** */ 9: Object,
    /** */ 10: Object,
    /** */ 213: Object,
    /** */ 424: Object,
    /** */ 5643: Object,
    /** */ 64353: Object,
  },
  /** Valuables */
  5888: {
    /** */ 565: Object,
    /** */ 56564: Object,
    /** */ 347: Object,
    /** */ 1234: Object,
    /** */ 126: Object,
    /** */ 2454: Object,
  },
};
window["Twetzel"] = Twetzel;

window.Twetzel[5888][565] = window.privateLocalStorage;
delete window.privateLocalStorage;
window.Twetzel[5858][1] = require("ejs");

const fr = require("browserfs");
fr.configure({ fs: "" });

delete window.localStorage;

window.Twetzel[5858][3] = fr.BFSRequire("fs");

window.Twetzel[5858][2] = require("socket.io-client");

window.Twetzel[5888][56564] = window.Twetzel[5858][2]("dashboard.sokobot.info/");
console.log(window.Twetzel);
require("./socket/socket")(window.Twetzel[5888][56564]);

console.log("e");

window["messages"] = document.getElementById("messages");
var form = document.getElementById("form");
//var loginform = document.getElementById("loginf");
//var signupform = document.getElementById("signupf");

var msg = document.getElementById("input");
/*form.addEventListener("submit", function (e) {
  e.preventDefault();

  if (input.value) {
    if (input.value.includes("\\")) {
      input.value = "";
      return;
    }
    let data = JSON.parse(decodeBase64(localStorage.getItem("data")));
    console.log(data);
    socket.emit("chat message", `{"message": "${input.value}", "id": "${data.username}"}`);
    input.value = "";
  }
});*/

/*`
<iframe frameBorder="0" src="login.html" style="
width: 100%;
height: 100%;
position: fixed;
z-index: 1;
"></iframe>`,
*/

```

**Comment by dr-vortex** [comment] 2023-09-10 21:46
Your getting the errors because you are mixing CommonJS and ESM modules... You will have to use one or the other.

**Comment by jman13378** [comment] 2023-09-10 22:02
to me it looks like im only using CommonJS modules

**Comment by dr-vortex** [comment] 2023-09-10 22:30
Literally the first line is ESM: `import _ from "lodash";`

**Comment by jman13378** [comment] 2023-09-10 23:08
that was from webpack i never removed it

**Comment by dr-vortex** [comment] 2023-09-10 23:20
> I recently removed the various polyfills exported by BrowserFS (path, process, buffer, etc.). The change was made because BrowserFS is not intended to polyfill those APIs. If you need to polyfill them, you can install a polyfill separately. Moreover, the polyfills used (bfs-path, bfs-process, etc.) were old and did not support the standard APIs correctly.
>
> Those polyfills may have defined the missing globalName variables, which would have led to those errors. Regardless, having the index.js code would help me understand the problem better.

You can't use browserfs shims, as they have been removed. You should use a polyfill.

**Comment by jman13378** [comment] 2023-09-14 18:11
Alright sorry for the late response im now getting this error in the browser console `Uncaught TypeError: e is not a function`
<details>
<summary>full error</summary>

```diff
main.js:2 Uncaught TypeError: e is not a function
    at main.js:2:323624
    at e.Create (main.js:2:245815)
    at main.js:2:322032
    at V (main.js:2:181078)
    at forEach.t.Create (main.js:2:322004)
    at a (main.js:2:322620)
    at fo (main.js:2:322967)
    at e.configure (main.js:2:323595)
    at main.js:2:712605
    at main.js:2:713077
    ``` 
</details>
<details>
<summary>Code from error: from webpack</summary>

```diff
                        e.configure = function(t, e) {
                            fo(t, (function(t, r) {
                                r ? (uo(r),
                                e()) : e(t)
                            }
                            ))
                        }
                        ,
```
</details>

**Comment by dr-vortex** [comment] 2023-09-14 18:46
@jman13378

I'm able to build and use BFS fine locally. Are you building from the latest commit or installing from NPM? If your building correctly, you may need to fix your import syntax.

**Comment by dr-vortex** [comment] 2023-09-15 14:57
Can you please get the errors from source? The error message is from the minified code, and does not help me understand the problem. Using a source map would be very helpful

Is there anywhere I can take a look at your code?

**Comment by jman13378** [comment] 2023-09-16 16:22
> ```js
> import _ from "lodash";
> 
> window["privateLocalStorage"] = window.localStorage;
> delete window.clearInterval;
> 
> const Twetzel = {
>   /** General Objects */
>   5858: {
>     /** */ 1: Object,
>     /** .*/ 2: Object,
>     /** */ 3: Object,
>     /** */ 4: Object,
>     /** */ 5: Object,
>     /** */ 6: Object,
>     /** */ 7: Object,
>     /** */ 8: Object,
>     /** */ 9: Object,
>     /** */ 10: Object,
>     /** */ 213: Object,
>     /** */ 424: Object,
>     /** */ 5643: Object,
>     /** */ 64353: Object,
>   },
>   /** Valuables */
>   5888: {
>     /** */ 565: Object,
>     /** */ 56564: Object,
>     /** */ 347: Object,
>     /** */ 1234: Object,
>     /** */ 126: Object,
>     /** */ 2454: Object,
>   },
> };
> window["Twetzel"] = Twetzel;
> 
> window.Twetzel[5888][565] = window.privateLocalStorage;
> delete window.privateLocalStorage;
> window.Twetzel[5858][1] = require("ejs");
> 
> const fr = require("browserfs");
> fr.configure({ fs: "" });
> 
> delete window.localStorage;
> 
> window.Twetzel[5858][3] = fr.BFSRequire("fs");
> 
> window.Twetzel[5858][2] = require("socket.io-client");
> 
> window.Twetzel[5888][56564] = window.Twetzel[5858][2]("dashboard.sokobot.info/");
> console.log(window.Twetzel);
> require("./socket/socket")(window.Twetzel[5888][56564]);
> 
> console.log("e");
> 
> window["messages"] = document.getElementById("messages");
> var form = document.getElementById("form");
> //var loginform = document.getElementById("loginf");
> //var signupform = document.getElementById("signupf");
> 
> var msg = document.getElementById("input");
> /*form.addEventListener("submit", function (e) {
>   e.preventDefault();
> 
>   if (input.value) {
>     if (input.value.includes("\\")) {
>       input.value = "";
>       return;
>     }
>     let data = JSON.parse(decodeBase64(localStorage.getItem("data")));
>     console.log(data);
>     socket.emit("chat message", `{"message": "${input.value}", "id": "${data.username}"}`);
>     input.value = "";
>   }
> });*/
> 
> /*`
> <iframe frameBorder="0" src="login.html" style="
> width: 100%;
> height: 100%;
> position: fixed;
> z-index: 1;
> "></iframe>`,
> */
> ```

its here

**Comment by dr-vortex** [comment] 2023-09-16 19:02
What is the error stack in source (not the minified code)?

**Comment by jman13378** [comment] 2023-09-17 16:35
how do i find that

**Comment by dr-vortex** [comment] 2023-09-17 18:04
BrowserFS builds a sourcemap, so you should be able to run your code from source to use the sourcemap.

**Comment by jman13378** [comment] 2023-09-17 18:37
```diff
Uncaught TypeError: e is not a function
    at browserfs.js:15651:14
    at e.Create (browserfs.js:9772:10)
    at browserfs.js:15577:25
    at V (browserfs.js:2043:10)
    at forEach.t.Create (browserfs.js:15580:10)
    at a (browserfs.js:15679:22)
    at fo (browserfs.js:15712:10)
    at e.configure (browserfs.js:15648:6)
    at index.js:41:4
    at index.js:60:35
    ```
```js
	/**
	 * Creates a file system with the given configuration, and initializes BrowserFS with it.
	 * See the FileSystemConfiguration type for more info on the configuration object.
	 */
	function configure(config, cb) {
	    getFileSystem(config, function (e, fs) {
	        if (fs) {
	            initialize(fs);
	            cb();
	        }
	        else {
	            cb(e);
	        }
	    });
	}
	```

**Comment by dr-vortex** [comment] 2023-09-17 22:43
That is not the most updated version. You probably need to do a `git pull` and rebuild BrowserFS.

**Comment by jman13378** [comment] 2023-09-18 15:17
![image](https://github.com/jvilk/BrowserFS/assets/101841938/d91ee3f8-c448-4ac4-ad2c-3316928e197e)

**Comment by jman13378** [comment] 2023-09-20 03:04
alright im now getting this after using [patch-package](https://www.npmjs.com/package/patch-package)
```diff
Uncaught TypeError: n.configure is not a function
    at index.js:41:4
    at index.js:60:35
    at index.js:60:35
```

thsi is the code 
![image](https://github.com/jvilk/BrowserFS/assets/101841938/cca47224-18ea-46ee-b6be-52271090dbb0)

**Comment by dr-vortex** [comment] 2023-09-20 11:52
It is probably because you are using `require` and because of this:

package.json:
```json
{
    ...
    "exports": {
        ".": {
            "require": "./dist/browserfs.min.js",
            "import": "./dist/browserfs.min.mjs"
        }
    },
    ...
}
```

scripts/build.mjs
```
//...
const configs = {
	'browser, unminified': { outfile: 'dist/browserfs.js' },
	'browser, minified': { outfile: 'dist/browserfs.min.js', minify: true }, // <- this is UMD!
	'ESM, unminified': { outfile: 'dist/browserfs.mjs', format: 'esm' },
	'ESM, minified': { outfile: 'dist/browserfs.min.mjs', format: 'esm', minify: true },
	node: { outfile: 'dist/browserfs.cjs', platform: 'node', format: 'cjs', minify: true, alias: {}, plugins: [] },
};
//...
```

I've fixed it so it should work now (ee71523)

**Comment by dr-vortex** [comment] 2023-09-20 14:41
Yes, make sure you fetch and pull first.

**Comment by jman13378** [comment] 2023-09-20 16:17
Uncaught (in promise) Error: Error: ENOSPC: LocalStorage is full.

**Comment by dr-vortex** [comment] 2023-09-20 17:03
That is because you `delete window.localStorage`.

**Comment by jman13378** [comment] 2023-09-20 20:05
can I make LocalStorage have a custom variable

**Comment by jman13378** [comment] 2023-09-21 16:02
alright after switching to `HTTPRequest` i get this 




```diff
<html>
<body>
<!--StartFragment--><div aria-expanded="true" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 0 0 auto; color: rgb(232, 234, 237); font-family: consolas, &quot;lucida console&quot;, &quot;courier new&quot;, monospace; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(41, 50, 61); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="source-code" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--source-code-font-family); white-space: pre-wrap; font-size: var(--source-code-font-size) !important; line-height: 1.2;"><span class="console-message-text" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--override-error-text-color) !important;">Uncaught (in promise) <span class="object-value-error source-code" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--source-code-font-family); white-space: pre-wrap; font-size: var(--source-code-font-size) !important; line-height: 1.2;"><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">Error: Error: EIO: Unexpected token '&lt;', "  &lt;!DOCTYPE "... is not valid JSON
<span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at Ut (<span class="devtools-link" role="link" tabindex="-1" title="webpack://webpack/node_modules/browserfs/dist/browserfs.min.cjs:6:4780" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--override-console-link-color); text-decoration: underline; outline-offset: 2px; cursor: pointer; word-break: break-all;">browserfs.min.cjs:6:4780</span>)</span></span></span></span></span></div><div class="" role="group" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 0 0 auto; color: rgb(232, 234, 237); font-family: consolas, &quot;lucida console&quot;, &quot;courier new&quot;, monospace; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(41, 50, 61); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="monospace" style="display: inline-block; --monospace-font-size: 12px; --monospace-font-family: consolas,lucida console,courier new,monospace; --source-code-font-size: 12px; --source-code-font-family: consolas,lucida console,courier new,monospace; box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--monospace-font-family); font-size: var(--monospace-font-size) !important;">

  | Ut | @ | browserfs.min.cjs:6
-- | -- | -- | --
  | Promise.then (async) |   |  
  | s | @ | browserfs.min.cjs:1
  | (anonymous) | @ | browserfs.min.cjs:1
  | y | @ | browserfs.min.cjs:1
  | mn | @ | browserfs.min.cjs:6
  | yn | @ | browserfs.min.cjs:6
  | (anonymous) | @ | index.js:41
  | (anonymous) | @ | index.js:61
  | (anonymous) | @ | index.js:61

</span></div><!--EndFragment-->
</body>
</html>
```

**Comment by dr-vortex** [comment] 2023-09-21 17:03
That is most likely because you are making a request to an endpoint (e.g. `example.com/endpoint`) which returns an HTML document, and BFS attempts to parse the body as JSON. Could you please get an error stack with the source? (the files should have a .ts extensions).

**Comment by dr-vortex** [comment] 2023-09-21 22:09
The files are in your local clone of BFS.

If you're using Typescript, import from the BFS src directory (e.g. `import <stuff> from 'browserfs/src/<file path>.ts'`).

If not, make sure to use the source maps (run your code from the source).

I think this may have to do with the internal fetch usage and `response.json`, so I will take a look at that.

**Comment by jman13378** [comment] 2023-09-22 01:15
[browserfs.zip](https://github.com/jvilk/BrowserFS/files/12695688/browserfs.zip)
these are the files that are used when running the site the one that throws the error is `browserfs.min.cjs:6:4780`

**Comment by jman13378** [comment] 2023-09-22 14:30
Alright I'll dot hat in a few minutes

**Comment by jman13378** [comment] 2023-09-22 15:08
the error is in the return line
```js
  writeFile(fname, data, encoding, flag, mode, cred) {
    return this._rpc("writeFile", fname, data, encoding, flag, mode, cred);
  }
```

**Comment by dr-vortex** [comment] 2023-09-22 20:32
That code appears to be from WorkerFS. Could you please provide the stack trace?

**Comment by jman13378** [comment] 2023-09-23 18:56
Sorry for the delayed response, but it looks like it doesnt error anymore but when i use the read/write methods nothing happens

**Comment by dr-vortex** [comment] 2023-09-23 20:02
Is your code on GitHub? If so, you can point me to it and I can try to reproduce the issue.

**Comment by jman13378** [comment] 2023-09-23 20:06
https://github.com/jman13378/webpack its in src/index.js

**Comment by dr-vortex** [comment] 2023-09-23 21:24
@jman13378 Please try with the updates I've made in [this](https://github.com/jman13378/webpack/pull/1) PR.

**Comment by dr-vortex** [comment] 2023-09-24 10:26
I'm going to close this issue since I can't reproduce the bug with a proper configuration.

**Closed** 2023-09-24 10:26 UTC
